PROMPT:
  - KEY: "JIRA-TASK"
    LABEL: "Jira task ID"
    DEFAULT_VALUE: "{{BRANCH_NAME}}"
  - KEY: "CHANGE"
    LABEL: "Type of change"
    OPTIONS:
      - VALUE: "feat :sparkles:"
        DESC: "A new feature"
      - VALUE: "fix :bug:"
        DESC: "A bug fix"
      - VALUE: "test :rotating_light:"
        DESC: "Adding missing tests or correcting wrong ones"
      - VALUE: "style :lipstick:"
        DESC: "A code change to improve clean code"
      - VALUE: "build-ci :construction-worker:"
        DESC: "Changes that affect the build system and/or CI configuratio files and scripts"
      - VALUE: "refactor :hammer:"
        DESC: "A code change"
      - VALUE: "docs :books:"
        DESC: "Documentation only changes"
      - VALUE: "chore :card_index:"
        DESC: "Changes that don't fit any of the options above"
  - KEY: "MESSAGE"
    LABEL: "Commit message"
  # - KEY: "LABEL"
  #   LABEL: "Label"
  #   OPTIONS:
  #     - VALUE: ""
  #       DESC: "No label"
  #     - VALUE: "[CI SKIP]"
  #       DESC: "Skip continous integration pipeline"
  #     - VALUE: "[WIP]"
  #       DESC: "Work In Progress"
# TEMPLATE: "{{JIRA-TASK}} ({{CHANGE}}): {{MESSAGE}}{{LABEL}}"
TEMPLATE: "{{JIRA-TASK}} ({{CHANGE}}): {{MESSAGE}}"
