name: terraform-docs

on: workflow_call

jobs:
  prepare:
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Detect documentation config-files' paths
        id: detect
        run: |
          # Detect terraform-docs files' paths
          paths=$(find . -name ".terraform-docs.yml" | sed -E "s#/[a-zA-Z.-]+\$##" | sort)

          # Build terraform job matrix with each subpath with terraform code to document
          matrix="[]"
          for path in $paths; do
            # NOTE output file detection is required since terraform-docs GH Action's default value overrides the value set in the config file
            output_file=$(grep -E "^  file:" $path/.terraform-docs.yml | sed -E "s/.*\:[\ ]*([0-9a-zA-Z.-_]+)\$/\1/")
            subpaths=$(find $path -maxdepth 2 -mindepth 2 -name "main.tf" | sed -E "s#/[a-zA-Z.-]+\$##" | sort)
            for subpath in $subpaths; do
              name=${subpath##*/}
              if [[ ${subpath%/*} == *modules ]]; then
                name="module $name"
              fi
              matrix=$(echo $matrix | jq -c --arg name "$name" --arg output_file "$output_file" --arg path $subpath '. += [{"name": $name, "outputFile": $output_file, "path": $path}]')
            done
          done

          # Set environments as output
          echo '::set-output name=matrix::'{"include":"$matrix"}
  generate-docs:
    name: "${{ matrix.name }}"
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    needs: [prepare]
    runs-on: self-hosted
    strategy:
      # NOTE parallel run is not possible due to race conditions when pushing changes to the branch
      max-parallel: 1
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v13.1
        with:
          files: '**.tf'
      - name: Generate terraform docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          config-file: ../.terraform-docs.yml
          git-commit-message: "docs: update ${{ matrix.name }} documentation [skip ci]"
          git-push: "true"
          output-file: ${{ matrix.outputFile }}
          working-dir: ${{ matrix.path }}
